### ISSUE TITLE
Investigate possible spec change

### ISSUE THREAD

**Issue by ZackWard** [ZackWard/react-tic-tac-toe#2]
I'm wrapping up work for this afternoon (getting ready to head to my other job) and have been considering an idea that I had. 

Would it be possible to move the requirement to implement the "bad-move notification" feature to day 2? I started working on it and realized that it would probably be more efficient to implement it after I move to the minimax algorithm. Then, it would just be a matter of looking at the potential play score versus their actual score. 

If the spec can't be changed, no worries, I'll get it knocked out regardless. 😄

**Comment by zealoushacker** [comment]
Absolutely the right move to get that into day 2!
