### ISSUE TITLE
Implement travis-ci based build and deployment to an aws s3 static site

### ISSUE THREAD

**Issue by zealoushacker** [ZackWard/react-tic-tac-toe#4]
If you have some time at the end, see if you could have the app be built with travis-ci and deployed automatically to an s3 bucket with a public-facing endpoint/URI.

**Comment by ZackWard** [comment]
I will look into this if I have extra time. I've been wanting to learn more about CI systems. I actually have an S3 bucket set up already that I can dust off. 👍

**Comment by ZackWard** [comment]
Ok, the site should be up at https://s3-us-west-2.amazonaws.com/zack-react-tic-tac-toe/index.html 😄
