### ISSUE TITLE
Running the build in dev vs running a dist build?

### ISSUE THREAD

**Issue by zealoushacker** [ZackWard/react-tic-tac-toe#6]
I was trying to run `$ yarn run build` or `$ yarn run start` after `$ yarn install`. No dice on either. I took a look at `package.json` and didn't find any `build` or `start` command defined, and only saw a `test` command. 🤔

**Comment by ZackWard** [comment]
Oops! I've just been running "webpack -w" in dev. Let me put that in the npm script.
