### ISSUE TITLE
Remove secrets from repo and use travis environment variables

### ISSUE THREAD

**Issue by zealoushacker** [ZackWard/react-tic-tac-toe#9]
This is *very* *very* bad news bears:

https://github.com/ZackWard/react-tic-tac-toe/blob/master/.travis.yml#L8

You don't want to commit your AWS secrets to the repo under any circumstances. I very strongly suggest that you revoke that AWS account key, generate a new set of credentials, and use Travis' environment variables to store them - because right now, I could overwrite your site by using that access key and secret. 👎 

Unless, and maybe I misunderstood, you have encrypted your aws secret. Still, I'd suggest to put it in environment variable rather than being hardcoded in the repo, because then you don't have to commit new stuff to the repo to change/update those credentials.

**Comment by ZackWard** [comment]
It is encrypted according to the travis docs.

**Comment by zealoushacker** [comment]
Still, I'd suggest using [environment variables](https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings) due to more flexibility.

**Comment by zealoushacker** [comment]
And due to less chance someone will go "aha this guy likes to put his secrets into gh repos, time to attack."

**Comment by ZackWard** [comment]
Yeah, less attack surface is always better. 😄 I'll work on getting that change made.

**Comment by ZackWard** [comment]
Ok, the original credentials have been revoked, new credentials generated, and moved into environment variables in the Travis CI project settings. I don't think that the original credentials were actually exposed, but as you say, this way is more flexible and potentially safer. 👍
